when: << pipeline.parameters.run-audiusd-workflow >>
jobs:
  - build-audiusd:
      context: github
  - test-audiusd-devnet:
      context: github
      requires:
        - build-audiusd
  - test-config-subcommands:
      context: github
      requires:
        - build-audiusd
  - publish-audius-ctl:
      context: github
      requires:
        - test-audiusd-devnet
        - test-config-subcommands
      filters:
        branches:
          only:
            - main
  - deploy-audiusd-staging:
      context: [github, dockerhub]
      requires:
        - publish-audius-ctl
      filters:
        branches:
          only:
            - main
  - deploy-audiusd-foundation-trigger:
      requires:
        - deploy-audiusd-staging
      type: approval
  - deploy-audiusd-foundation:
      context: [github, dockerhub]
      requires:
        - deploy-audiusd-foundation-trigger
  - deploy-audiusd-sps-trigger:
      requires:
        - deploy-audiusd-foundation
      type: approval
  - deploy-audiusd-sps:
      context: [github, dockerhub]
      requires:
        - deploy-audiusd-sps-trigger
